@startuml

title __REPOSITORY's Class Diagram__\n

  namespace com.skhatoll.backend {
    namespace repository {
      interface com.skhatoll.backend.repository.EnamoradosRepository {
          {abstract} + existsByIdSala()
          {abstract} + findByIdSala()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace repository {
      interface com.skhatoll.backend.repository.HabilidadSalaRepository {
          {abstract} + findByIdSalaUsuario_IdSalaUsuarioAndNombre()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace repository {
      interface com.skhatoll.backend.repository.RolRepository {
          {abstract} + findByBando()
          {abstract} + findByNombre()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace repository {
      interface com.skhatoll.backend.repository.SalaRepository {
          {abstract} + existsByCodigoSala()
          {abstract} + findByCodigoSala()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace repository {
      interface com.skhatoll.backend.repository.SalaUsuarioRepository {
          {abstract} + countBySala_IdSala()
          {abstract} + existsBySala_IdSalaAndUsuario_IdUsuario()
          {abstract} + findBySala_IdSala()
          {abstract} + findBySala_IdSalaAndIdModelo()
          {abstract} + findBySala_IdSalaAndUsuario_IdUsuario()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace repository {
      interface com.skhatoll.backend.repository.SesionVotacionRepository {
          {abstract} + existsBySala_IdSalaAndAbiertaTrue()
          {abstract} + findBySala_IdSala()
          {abstract} + findBySala_IdSalaAndAbiertaTrue()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace repository {
      interface com.skhatoll.backend.repository.UsuarioRepository {
          {abstract} + existsByNombre()
          {abstract} + findByNombre()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace repository {
      interface com.skhatoll.backend.repository.VotoRepository {
          {abstract} + countBySesion_IdSesionAndObjetivo_IdUsuario()
          {abstract} + findBySesion_IdSesion()
          {abstract} + findBySesion_IdSesionAndVotante_IdUsuario()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
