@startuml

title __CONSTANTS's Class Diagram__\n

  namespace com.skhatoll.backend {
    namespace util.constants {
      class com.skhatoll.backend.util.constants.ErrorMessages {
          {static} + HABILIDAD_YA_USADA : String
          {static} + JUGADOR_ELIMINADO : String
          {static} + JUGADOR_NO_EN_SALA : String
          {static} + PARTIDA_NO_INICIADA : String
          {static} + SALA_NO_ENCONTRADA : String
          {static} + SESION_YA_CERRADA : String
          {static} + SOLO_NARRADOR : String
          {static} + USUARIO_NO_ENCONTRADO : String
          {static} + VOTACION_NO_ENCONTRADA : String
          {static} + VOTACION_YA_ABIERTA : String
          - ErrorMessages()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace util.constants {
      class com.skhatoll.backend.util.constants.GameConstants {
          {static} + BANDO_ALDEA : String
          {static} + BANDO_LOBO : String
          {static} + HAB_DISPARO : String
          {static} + HAB_ESPIAR : String
          {static} + HAB_FLECHAZO : String
          {static} + HAB_MODELO : String
          {static} + HAB_POCION_MUERTE : String
          {static} + HAB_POCION_VIDA : String
          {static} + HAB_VISION : String
          {static} + RES_ELIMINADO : String
          {static} + RES_ENAMORADOS : String
          {static} + RES_LISTA_SOSPECHOSOS : String
          {static} + RES_MODELO_ASIGNADO : String
          {static} + RES_REVIVIDO : String
          {static} + RES_ROL_REVELADO : String
          {static} + ROL_ALDEANO : String
          {static} + ROL_BRUJA : String
          {static} + ROL_CAZADOR : String
          {static} + ROL_CUPIDO : String
          {static} + ROL_LOBO : String
          {static} + ROL_NINA : String
          {static} + ROL_NINO_SALVAJE : String
          {static} + ROL_SIN_ROL : String
          {static} + ROL_VIDENTE : String
          {static} + WS_ALCALDE : String
          {static} + WS_EVENTO_ALCALDE_ELEGIDO : String
          {static} + WS_EVENTO_CAMBIO_FASE : String
          {static} + WS_EVENTO_COMPANEROS_LOBOS : String
          {static} + WS_EVENTO_JUGADOR_SALIO : String
          {static} + WS_EVENTO_JUGADOR_UNIDO : String
          {static} + WS_EVENTO_PARTIDA_INICIADA : String
          {static} + WS_EVENTO_ROL_ASIGNADO : String
          {static} + WS_EVENTO_ROL_CAMBIADO : String
          {static} + WS_EVENTO_VOTACION_ABIERTA : String
          {static} + WS_EVENTO_VOTACION_CERRADA : String
          {static} + WS_EVENTO_VOTOS_ACTUALIZADOS : String
          {static} + WS_FASE : String
          {static} + WS_FIN : String
          {static} + WS_MUERTE : String
          {static} + WS_QUEUE_LOBOS : String
          {static} + WS_QUEUE_ROL : String
          {static} + WS_SALA : String
          {static} + WS_SALA_INICIO : String
          {static} + WS_VOTACION : String
          {static} + WS_VOTOS : String
          - GameConstants()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
