@startuml

title __SALA's Class Diagram__\n

  namespace com.skhatoll.backend {
    namespace dto.sala {
      class com.skhatoll.backend.dto.sala.AsignarNarradorRequest {
          - idUsuario : Integer
          + AsignarNarradorRequest()
          + equals()
          + getIdUsuario()
          + hashCode()
          + setIdUsuario()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace dto.sala {
      class com.skhatoll.backend.dto.sala.CrearSalaResponse {
          - codigoSala : String
          + CrearSalaResponse()
          + equals()
          + getCodigoSala()
          + hashCode()
          + setCodigoSala()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace dto.sala {
      class com.skhatoll.backend.dto.sala.JugadorDto {
          - codigoUuid : String
          - esAlcalde : Boolean
          - esNarrador : boolean
          - estaVivo : Boolean
          - idUsuario : Integer
          - nombre : String
          + JugadorDto()
          + equals()
          + getCodigoUuid()
          + getEsAlcalde()
          + getEstaVivo()
          + getIdUsuario()
          + getNombre()
          + hashCode()
          + isEsNarrador()
          + setCodigoUuid()
          + setEsAlcalde()
          + setEsNarrador()
          + setEstaVivo()
          + setIdUsuario()
          + setNombre()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace dto.sala {
      class com.skhatoll.backend.dto.sala.JugadorRolDto {
          - bando : String
          - codigoUuid : String
          - estaVivo : Boolean
          - idUsuario : Integer
          - nombre : String
          - nombreRol : String
          + JugadorRolDto()
          + equals()
          + getBando()
          + getCodigoUuid()
          + getEstaVivo()
          + getIdUsuario()
          + getNombre()
          + getNombreRol()
          + hashCode()
          + setBando()
          + setCodigoUuid()
          + setEstaVivo()
          + setIdUsuario()
          + setNombre()
          + setNombreRol()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace dto.sala {
      class com.skhatoll.backend.dto.sala.UnirseRequest {
          - codigoSala : String
          + UnirseRequest()
          + equals()
          + getCodigoSala()
          + hashCode()
          + setCodigoSala()
          + toString()
          # canEqual()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
