@startuml

title __CONTROLLER's Class Diagram__\n

  namespace com.skhatoll.backend {
    namespace controller {
      class com.skhatoll.backend.controller.AuthController {
          + AuthController()
          + login()
          + registro()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace controller {
      class com.skhatoll.backend.controller.PartidaController {
          + PartidaController()
          + abrirVotacion()
          + cambiarFase()
          + cerrarPartida()
          + cerrarVotacion()
          + confirmarMuerte()
          + getEstadoPartida()
          + getSesionActiva()
          + usarHabilidad()
          + votar()
      }
    }
  }
  

  namespace com.skhatoll.backend {
    namespace controller {
      class com.skhatoll.backend.controller.SalaController {
          + SalaController()
          + asignarNarrador()
          + crearSala()
          + getJugadores()
          + getJugadoresConRol()
          + iniciarPartida()
          + salirDeSala()
          + unirse()
      }
    }
  }
  

  com.skhatoll.backend.controller.AuthController o-- com.skhatoll.backend.service.interfaces.auth.IAuthService : authService
  com.skhatoll.backend.controller.PartidaController o-- com.skhatoll.backend.service.interfaces.partida.IPartidaService : partidaService
  com.skhatoll.backend.controller.SalaController o-- com.skhatoll.backend.service.interfaces.jugador.IJugadorService : jugadorService
  com.skhatoll.backend.controller.SalaController o-- com.skhatoll.backend.service.interfaces.sala.ISalaService : salaService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
